### ISSUE TITLE
'HTTPHandler' has no attribute 'open'

### ISSUE THREAD

**Issue by rxaviers** [metajack/notify-webhook#10]
[`opener = urllib.request.HTTPHandler`](https://github.com/metajack/notify-webhook/blob/98b98039f1aeaafd1f122aaf460965f300202e30/notify-webhook.py#L270). But, `HTTPHandler` has no `open` method. So, [`u = opener.open(request)`](https://github.com/metajack/notify-webhook/blob/98b98039f1aeaafd1f122aaf460965f300202e30/notify-webhook.py#L298) is unlikely to work.

    <class 'urllib.request.HTTPHandler'>
    Traceback (most recent call last):
      File "hooks/post-receive", line 313, in <module>
        post(POST_URL, data)
      File "hooks/post-receive", line 301, in post
        u = opener.open(request)
    AttributeError: type object 'HTTPHandler' has no attribute 'open'

**Comment by rxaviers** [comment]
I have low experience programming on python. But, `opener = urllib.request.build_opener(urllib.request.HTTPHandler)` worked for me.

**Comment by robbat2** [comment]
Fixed.
