### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by rxaviers** [metajack/notify-webhook#12]
I encourage you to create tags (especially following [semver][]) to allow users to pick stable versions.

[semver]: http://semver.org/

**Comment by robbat2** [comment]
Release v0.1.0 tagged now.

P.S, your fork's master branch can be updated again; The issue raised in PR#9 was fixed in a cleaner way.

**Comment by lkraav** [comment]
@robbat2 maybe another release tag now? https://packages.gentoo.org/packages/dev-vcs/notify-webhook looks like has 0.1.0 from 2015.
